services:
  redis:
    ports:
      - "6381:6379"  # ðŸ‘ˆ RedisInsight access
  
  api:
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "4000:4000"
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules